# Generated by Django 3.2.7 on 2021-09-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
